language: php

php:
  - "7.2"
  - "7.3"
  - "7.4"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
    vendor/bin/phpunit  --coverage-clover=coverage.xml

after_script:
  - if [ $(phpenv version-name) == "7.2" ]; then bash <(curl -s https://codecov.io/bash) ; fi
  - if [ $(phpenv version-name) == "7.2" ]; then wget https://scrutinizer-ci.com/ocular.phar -O build/ocular.phar ; fi
  - if [ $(phpenv version-name) == "7.2" ]; then php build/ocular.phar code-coverage:upload --format=php-clover coverage.xml ; fi
